### ISSUE TITLE
Dataloaders and training speed

### ISSUE THREAD

**Issue by Abc11c** [jayLEE0301/vq_bet_official#5]
Hi @jayLEE0301, 

Thank you for releasing the code! I wanted to quickly benchmark the non-goal conditioned ant env, but the training feels slow, am I missing something ? 

Is it because we are not using `num_workers` in the [dataloaders](https://github.com/jayLEE0301/vq_bet_official/blob/09d4851288ca5deaaa1ab367a208e520f8ee9a84/examples/train.py#L35)?  

Am I missing something ? I'm trying to run this on `NVIDIA RTX A6000` with torch version `1.12.1+cu116`

When I try to pin the memory and change the `num_workers` in the dataloader I get the following error

```
Traceback (most recent call last):
  File "/home/USER/working/vq_bet_official/examples/train.py", line 162, in main
    for data in test_loader:
  File "/home/USER/.conda/envs/vq-bet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/USER/.conda/envs/vq-bet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/USER/.conda/envs/vq-bet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/USER/.conda/envs/vq-bet/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/USER/.conda/envs/vq-bet/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/USER/.conda/envs/vq-bet/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/USER/.conda/envs/vq-bet/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/USER/working/vq_bet_official/examples/dataset.py", line 405, in __getitem__
    if self.dataset[i][0].ndim > 2:
  File "/home/USER/.conda/envs/vq-bet/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 290, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/USER/working/vq_bet_official/examples/dataset.py", line 264, in __getitem__
    T = self.masks[idx].sum().int().item()
RuntimeError: CUDA error: initialization error
```

Any help regarding the same

Thanks!

**Comment by jayLEE0301** [comment]
Hello @Abc11c 
Thank you for your interest in our project.

Do you have any idea how long it takes to learn ant environment on your machine?
(I remember that it usually takes 1-2 days on our machine (A5000/A6000.)

**Comment by Abc11c** [comment]
Hi,

It roughly takes about 3-4 mins per epoch, and overall it takes about 20hours to train while skipping the `eval_on_env`, is there any way to speed things up? 

Is it cause of of the 100 step window for ant env the ur3 is relatively faster cause of 10 steps window?

Thanks!

**Comment by jayLEE0301** [comment]
Sorry for the late reply.
Our training on the ANT environment also took about a day, so it seems to be similar to yours.

As you mentioned, the large length of the prediction could be one of the reason for the long training time in ANT. If you want to experiment with the time/performance tradeoff, you could try adjusting the length of the sequence you are predicting, or adjusting the size of the GPT.

**Comment by Abc11c** [comment]
Thank you for your answers, 

How can I generate an image similar to Figure 1, which shows rollouts for the Push-T environment?

I assume that after training, the environment should be initialized with a random position. Then, multiple rounds of unconditional rollouts should be performed while keeping the start position fixed.

Is there a sample script that does the same 

Thanks!

**Comment by jayLEE0301** [comment]
As you said, I anchored the T-block to a specific point, 45 degrees to the top right of the goal point, and then rolled it out again and again.

Then, I draw the trajectory in trajectories by:

```
    for trajectory in trajectories:
        cmap = cm.get_cmap('plasma')
        norm = colors.Normalize(vmin=0, vmax=len(trajectory)-1)

        for i in range(len(trajectory) - 1):
            # Scale points
            x1, y1 = scale(trajectory[i][0], img_dim, data_min, data_max), scale(trajectory[i][1], img_dim, data_min, data_max)
            x2, y2 = scale(trajectory[i+1][0], img_dim, data_min, data_max), scale(trajectory[i+1][1], img_dim, data_min, data_max)
            color = cmap(norm(i))
            plt.plot([x1, x2], [y1, y2], color=color)
```
